democonnector1:
  name: DemoConnector1
  scopes:
    - ids_connector
  attributes:
    ids-attributes:
      security_profile:
        audit_logging: 2
      ids_membership: true
      ids-uri: "http://some-uri"
      transportCertsSha256: "bacb879575730bb083f283fd5b67a8cb896944d1be28c7b32117cfc757c81e96"
reclaimid:
  name: re:claimID
  scopes:
    - openid
  redirect_uri: https://ui.reclaim/jwt_fhg
  user_attributes:
    - photo
    - usercertificate;binary
    - fullname
