---
- client_id: testClient
  name: omejdn admin ui
  allowed_scopes:
  - omejdn:admin
  redirect_uri: http://localhost:4200
  attributes: []
- client_id: testClient2
  name: omejdn admin ui
  allowed_scopes:
  - omejdn:admin
  redirect_uri: http://localhost:4200
  attributes: []
