---
issuer: http://localhost:4567
front_url: http://localhost:4567
no_password_login: true
bind_to: 0.0.0.0:4567
environment: development
openid: true
default_audience: ''
accept_audience: http://localhost:4567
access_token:
  expiration: 3600
  algorithm: RS256
id_token:
  expiration: 3600
  algorithm: RS256
plugins:
  user_backend_yaml:
    location: config/users.yml
  token_user_attributes:
  admin_api:
  user_selfservice:
  federation:
    providers:
      fraunhofer:
        issuer: http://sso.fraunhofer.de/auth/realms/FHG-ZD
        description: Login with Fraunhofer SSO
        op_logo_uri: https://sso.fraunhofer.de/auth/resources/9vzl8/welcome/fhg/img/fhg_logo.png
        client_id: myAwesomeClientId
        token_endpoint_auth_method: private_key_jwt
        client_secret: mySuperSecretSecret
        scope:
        - openid
        - profile
      reclaim:
        issuer: http://localhost:7776
        description: Login with re:claimID
        op_logo_uri: https://www.gnunet.org/images/reclaim_logo.png
        client_id: 000G005G728GN89BJ2GBRQK1QFXN76MAWRMMHY8BKNQQ9PVK721XJJ7ATR
        token_endpoint_auth_method: client_secret_basic
        client_secret: secret
        scope:
        - openid
        - profile
        attribute_mappers:
        - reclaim_mapper
      omejdn:
        issuer: http://localhost:4568
        description: Login with Omejdn
        op_logo_uri: http://localhost:4567/img/logo.jpg
        client_id: myAwesomeClientId
        token_endpoint_auth_method: private_key_jwt
        client_secret: mySuperSecretSecret
        scope:
        - openid
        - profile
        - omejdn:admin
        attribute_mappers:
        - static_mapper
        - clone_mapper
    attribute_mappers:
      static_mapper:
        type: static
        prerequisites:
          omejdn: hello
        attributes:
        - key: omejdn
          value: admin
      clone_mapper:
        type: clone
        mapping:
        - from: omejdn
          to: omejdn
      reclaim_mapper:
        type: clone
        mapping:
        - from: given_name
          to: given_name
        - from: family_name
          to: family_name
user_backend_default: yaml
