---
- username: testUser
  scopes:
  - omejdn:admin
  - openid
  - profile
  attributes:
  - key: email
    value: admin@example.com
  - key: omejdn
    value: admin
  - key: exampleKey
    value: exampleValue
  password: "$2a$12$0apoKS5lzSDI5zETS2Aa/OOFpbN7b3c/ZKfGc1coYQw6SRytbQM5S"

