name: build-server
on:
  push:
    paths:
      - "**"
      - ".github/workflows/build-server.yml"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Rubocop Lint
      run: |
        sudo gem install --no-document rubocop
        rubocop
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build docker image
      run: |
        docker build -t ghcr.io/fraunhofer-aisec/omejdn-server:dev .
    - name: Push Docker Image
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/fraunhofer-aisec/omejdn-server:dev
      if: github.ref == 'refs/heads/master'
    - name: Push release docker image
      run: |
        # determine version from tag
        export VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
        if [[ $VERSION != v* ]]
        then
          export VERSION=""
          echo "Building version-less (master or feature branch)"
        else
          # make version more Java-friendly by dropping the 'v'
          export VERSION=${VERSION:1:${#VERSION}}
          echo "Building as ${VERSION}"
        fi
        echo "##[set-output name=version;]$VERSION"
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker tag ghcr.io/fraunhofer-aisec/omejdn-server:dev ghcr.io/fraunhofer-aisec/omejdn-server:$VERSION
        docker tag ghcr.io/fraunhofer-aisec/omejdn-server:dev ghcr.io/fraunhofer-aisec/omejdn-server:latest
        docker push ghcr.io/fraunhofer-aisec/omejdn-server:$VERSION
        docker push ghcr.io/fraunhofer-aisec/omejdn-server:latest
      id: push_release_docker
      if: startsWith(github.ref, 'refs/tags/v')
    - name: "Create Release"
      if: startsWith(github.ref, 'refs/tags/v')
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ steps.push_release_docker.outputs.version }}
        draft: false
        prerelease: false
