name: build-server
on:
  push:
    paths:
      - "**"
      - ".github/workflows/build-server.yml"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Rubocop Lint
      run: |
        sudo gem install --no-document rubocop
        rubocop
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Docker Image
      run: |
        export TAG=`expr substr $GITHUB_SHA 1 8`
        docker build -t ghcr.io/fraunhofer-aisec/omejdn-server:$TAG .
    - name: Push Docker Image
      run: |
        export TAG=`expr substr $GITHUB_SHA 1 8`
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/fraunhofer-aisec/omejdn-server:$TAG
      if: github.ref == 'refs/heads/master'
