name: build-server
on:
  push:
    paths:
      - "**"
      - ".github/workflows/build-server.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Docker Image
      run: |
        export TAG=`expr substr $GITHUB_SHA 1 8`
        docker build -t docker.pkg.github.com/fraunhofer-aisec/omejdn/server:$TAG .
    - name: Push Docker Image
      run: |
        export TAG=`expr substr $GITHUB_SHA 1 8`
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/fraunhofer-aisec/omejdn-server:$TAG
      if: github.ref == 'refs/heads/master'
    - uses: actions/delete-package-versions@v1
      with:
        package-name: server
        num-old-versions-to-delete: 1
      if: github.ref == 'refs/heads/master'
