name: Pull Request Test Build
on:
  pull_request:
    paths:
      - "**"
      - ".github/workflows/build-server.yml"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Rubocop lint
      run: |
        sudo gem install --no-document rubocop
        rubocop
    - name: Unit tests
      run: |
        gem install --no-document test-unit rack-test webrick
        bundle exec ruby tests/test_admin_api.rb
        bundle exec ruby tests/test_selfservice_api.rb
        bundle exec ruby tests/test_oauth_helper.rb

